# Generated by Django 4.2.3 on 2023-07-17 02:26

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('isbn', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('lib_card', models.BigIntegerField(null=True, unique=True)),
                ('fees', models.FloatField(default=0)),
                ('member_since', models.DateTimeField()),
                ('signed_out', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='database.book')),
            ],
        ),
        migrations.CreateModel(
            name='BooksAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField(default=0)),
                ('copies', models.IntegerField(default=1)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='database.book')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(default=database.models.Activity.loan_date_time)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
