# Generated by Django 4.2.3 on 2023-07-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='database.booksavailable')),
            ],
            options={
                'ordering': ['branch_name'],
            },
        ),
    ]
