# Generated by Django 4.2.3 on 2023-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_librarybranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='booksavailable',
            name='copies',
            field=models.IntegerField(default=0),
        ),
    ]
