# Generated by Django 4.2.3 on 2023-07-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_book_isbn_alter_activity_loan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='librarybranch',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.book'),
        ),
    ]
