# Generated by Django 4.2.3 on 2023-09-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_activity_user_activity_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signed_out',
            field=models.ManyToManyField(blank=True, max_length=5, to='database.activity'),
        ),
    ]
