# Generated by Django 4.2.3 on 2023-07-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_book_summary_alter_booksavailable_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
