# Generated by Django 4.2.3 on 2023-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_book_copies_librarybranch_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lib_card',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
