# Generated by Django 4.2.3 on 2023-09-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_user_signed_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.librarybranch'),
        ),
    ]
