# Generated by Django 4.2.3 on 2023-07-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_lib_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybranch',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.librarybranch'),
        ),
    ]
