# Generated by Django 4.2.3 on 2023-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_librarybranch_books_book_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
    ]
