# Generated by Django 4.2.3 on 2023-07-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_book_cover_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
