# Generated by Django 4.2.3 on 2023-07-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_book_cover_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
