# Generated by Django 4.2.3 on 2023-07-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ManyToManyField(to='database.librarybranch'),
        ),
    ]
