# Generated by Django 4.2.3 on 2023-07-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_librarybranch_options_remove_book_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_loan',
            field=models.IntegerField(default=0),
        ),
    ]
