# Generated by Django 4.2.3 on 2023-07-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_book_on_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='on_loan',
            new_name='available',
        ),
    ]
