# Generated by Django 4.2.3 on 2023-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_book_options_alter_librarybranch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='on_loan',
            field=models.IntegerField(default=0),
        ),
    ]
