# Generated by Django 4.2.3 on 2023-07-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_on_loan_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
    ]
