# Generated by Django 4.2.3 on 2023-07-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_book_on_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='on_loan',
            field=models.IntegerField(null=True),
        ),
    ]
