# Generated by Django 4.2.3 on 2023-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_remove_book_on_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_loan',
            field=models.IntegerField(default=1),
        ),
    ]
